### ISSUE TITLE
Make landing pages for intermediate hierarchy pages more easily accessible.

### ISSUE THREAD

**Issue by ndtl** [NanoDesuTranslations/generator#6]
Right now if I have Volume 1--> Chapter 1--> Part 1, I can't easily navigate to the Chapter 1 page since clicking on the dropdown menu just opens up the next sub-menu in the hierarchy. I'd like it so that clicking on Chapter 1 brings you to the Chapter 1 page, while hovering a mouse over Chapter 1 shows you the Part 1 submenu. 

This is not super high priority, but is something I would like to have eventually done.

**Comment by nanodesutl** [comment]
you can now click the dot to the left of an item in the dropdown menu to go to that page
